"""empty message

Revision ID: 4aab8a6cfcd3
Revises: 
Create Date: 2022-05-16 12:06:49.238577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4aab8a6cfcd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_graphic_profiles',
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('primary_color_hex', sa.String(), nullable=True),
    sa.Column('accent_color_hex', sa.String(), nullable=True),
    sa.Column('background_color_hex', sa.String(), nullable=True),
    sa.Column('header_image_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_table('building_modules',
    sa.Column('building_module_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('building_module_id')
    )
    op.create_table('buildings',
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('building_name', sa.String(), nullable=True),
    sa.Column('licensee_id', sa.String(), nullable=True),
    sa.Column('user_app_self_registration', sa.Integer(), nullable=True),
    sa.Column('tenant_registration_code', sa.Integer(), nullable=True),
    sa.Column('private_building', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('postal_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('square_meters', sa.Integer(), nullable=True),
    sa.Column('number_of_users', sa.Integer(), nullable=True),
    sa.Column('number_of_floors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('building_id'),
    sa.UniqueConstraint('tenant_registration_code')
    )
    op.create_table('licensees',
    sa.Column('licensee_id', sa.String(), nullable=False),
    sa.Column('licensee_name', sa.String(), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('licensee_id')
    )
    op.create_table('modules',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=True),
    sa.Column('module_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('order_lines',
    sa.Column('order_line_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('parent_order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('order_line_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('product_price_ex_vat', sa.Float(), nullable=True),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.Column('product_price_incl_vat', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('total_amount_ex_vat', sa.Float(), nullable=True),
    sa.Column('total_amount_incl_vat', sa.Float(), nullable=True),
    sa.Column('total_subsidy_amount_incl_vat', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('order_line_id')
    )
    op.create_table('orders',
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('pos_id', sa.String(), nullable=False),
    sa.Column('order_reference', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('total_amount_ex_vat', sa.Float(), nullable=True),
    sa.Column('total_vat_amount', sa.Float(), nullable=True),
    sa.Column('total_amount_incl_vat', sa.Float(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('payment_status_id', sa.Integer(), nullable=True),
    sa.Column('cash_order', sa.Integer(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_full_name', sa.String(), nullable=True),
    sa.Column('ordered_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('organisations',
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.Column('organisation_name', sa.String(), nullable=False),
    sa.Column('organisation_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('organisation_id'),
    sa.UniqueConstraint('organisation_number')
    )
    op.create_table('payment_methods',
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_name', sa.String(), nullable=True),
    sa.Column('cash_payment', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('payment_method_id')
    )
    op.create_table('payment_statuses',
    sa.Column('payment_status_id', sa.Integer(), nullable=False),
    sa.Column('payment_status_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('payment_status_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_statuses')
    op.drop_table('payment_methods')
    op.drop_table('organisations')
    op.drop_table('orders')
    op.drop_table('order_lines')
    op.drop_table('modules')
    op.drop_table('licensees')
    op.drop_table('buildings')
    op.drop_table('building_modules')
    op.drop_table('building_graphic_profiles')
    # ### end Alembic commands ###
