"""empty message

Revision ID: 8c8ccfd58ba4
Revises: 26e0f8998dda
Create Date: 2022-05-20 05:46:12.665746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c8ccfd58ba4'
down_revision = '26e0f8998dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosks',
    sa.Column('kiosk_id', sa.String(), nullable=False),
    sa.Column('kiosk_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('service_provider_id', sa.String(), nullable=True),
    sa.Column('building_module_id', sa.Integer(), nullable=True),
    sa.Column('building_id', sa.String(), nullable=True),
    sa.Column('thumbnail_image_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('header_image_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organisation_id', sa.String(), nullable=True),
    sa.Column('service_provider_internal_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('kiosk_id')
    )
    op.create_table('points_of_sales',
    sa.Column('pos_id', sa.String(), nullable=False),
    sa.Column('pos_name', sa.String(), nullable=True),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pos_id', 'store_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points_of_sales')
    op.drop_table('kiosks')
    # ### end Alembic commands ###
